# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    displayName: "Build and push docker image to Docker Hub"
    inputs:
      containerRegistry: "dockerhub"
      repository: "acoskun17/aicoredevops"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      tags: "v2"

  - task: KubernetesManifest@1
    displayName: "Start container on Azure Kubernetes Cluster (AKS)"
    inputs:
      action: "deploy"
      connectionType: "azureResourceManager"
      azureSubscriptionConnection: "networkingresgrp"
      azureResourceGroup: "networking-resource-group"
      kubernetesCluster: "terraform-aks-cluster"
      manifests: "kubernetes-manifest/application-manifest.yaml"